name: Local Build Docker Image

on:
    push:
        branches:
            - main

jobs:
    local_build_docker_image:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2

            -   name: Build image
                run: docker build . -t splitter

            -   name: Test Docker image
                run: docker run splitter
