name: 'Self Test With Tag'

on: [push]

jobs:
    self_test_with_tag:
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                with:
                    fetch-depth: 0

            # see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

            # see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
            # this create $TAG environment value
            -   run: echo "TAG=${{ steps.previous_tag.outputs.tag }}" >> $GITHUB_ENV

            -
                # Uses an action in the root directory
                uses: ./
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    TAG: ${TAG}
                with:
                    package-directory: 'tests/packages/some-package'
                    split-repository-organization: 'TomasVotruba'
                    split-repository-name: 'github-action-monorepo-split-test'
