name: Split Test

on:
    push:
        branches:
            - main

        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

        release:
            types: [created]

jobs:
    split_test:
        runs-on: ubuntu-latest

        steps:
            -
                # debug
                run: echo ${{ github.event_name }}

            -
                # debug
                run: echo ${{ github.event.action }}

            -
                uses: actions/checkout@v2

            -
                # run action.yaml in the root directory
                # see https://github.community/t/self-reference-an-action-for-testing/17891
                uses: "./"
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'tests/packages/some-package'
                    split-repository-organization: 'symplify'
                    split-repository-name: 'monorepo-split-github-action-test'
                    # change to use that should be signed under the split commit
                    user-name: 'kaizen-ci'
                    user-email: 'info@kaizen-ci.org'
